name: 'nyc_taxi'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi:
    gold:
      +materialized: table
      +schema: gold